TOPICS_GENERAL = [
    "Science - physics, chemistry, biology, astronomy, etc.",
    "Mathematics - algebra, geometry, calculus, statistics, etc.",
    "Technology - computers, engineering, AI, robotics, etc.",
    "Business - economics, finance, marketing, management, entrepreneurship",
    "History - ancient, medieval, modern, world history, military history",
    "Geography - countries, capitals, landscapes, maps, oceans, rivers",
    "Literature - poetry, novels, plays, short stories, genres, authors",
    "Philosophy - logic, ethics, political philosophy, existentialism",
    "Psychology - cognition, development, disorders, therapy, social psychology",
    "Sociology - culture, demographics, institutions, social change, inequality",
    "Politics - political systems, ideologies, voting, campaigns, public policy",
    "Law - constitutional law, criminal law, contracts, litigation, civil rights",
    "Medicine - anatomy, diseases, treatments, pharmaceuticals, medical specialties",
    "Religion - Christianity, Islam, Judaism, Buddhism, Hinduism, atheism",
    "Mythology - Greek, Roman, Norse, Egyptian, Native American myths",
    "Art - art history, painting, sculpture, architecture, music, theater",
    "Sports - individual and team sports, athletes, championships, training",
    "Cooking - recipes, ingredients, techniques, regional and ethnic cuisine",
    "Movies & TV - genre analysis, directors, actors, awards, popular shows",
    "News & Current Events - reporting on latest happenings around the world",
    "Culture - customs, values, gender roles, holidays, language, clothing",
    "Relationships - family, friends, romantic relationships, dating, marriage",
    "Education - teaching methods, curriculum, policy, higher education, vocational",
    "Transportation - cars, planes, trains, ships, public transit, infrastructure",
    "Communication - language acquisition, linguistics, rhetoric, social media",
    "Agriculture - farming techniques, crops, livestock, fisheries, forestry",
    "Housing & Architecture - interior design, urban planning, real estate, remodeling",
    "Nature & Environment - ecology, sustainability, conservation, renewable energy",
    "Travel & Tourism - destinations, lodging, adventure, culture, ecotourism",
    "Music - theory, genres, instruments, bands, composers, music history",
    "Fashion - designers, trends, modeling, retail, cosmetics, accessories",
    "Government - political systems, public administration, foreign policy, voting",
    "Warfare - military history, weapons, strategy, special operations forces",
    "Space - astronomy, spaceflight, exploration, space technology, universe",
    "Weather & Climate - meteorology, forecasting, natural disasters, seasons",
    "Food & Cooking - nutrition, recipes, diets, food science, restaurants",
    "Pets & Animals - breeds, care, veterinary medicine, wildlife, animal behavior",
    "Gardening - plants, landscaping, flowers, vegetables, lawn care, tools",
    "Home Improvement - repair, decor, renovation, tools, plumbing, electricity",
    "Personal Finance - budgeting, investing, taxes, insurance, retirement",
    "Exercise & Fitness - techniques, equipment, sports medicine, motivation",
    "Health & Medicine - biology, anatomy, diseases, treatments, wellness",
    "Mental Health - psychology, disorders, counseling, self-help, mindfulness",
    "Race & Ethnicity - cultures, discrimination, identity, immigration, diversity",
    "Gender & Sexuality - LGBTQ issues, feminism, roles, relationships, equality",
    "Employment - careers, human resources, resumes, workplace culture, unions",
    "Crime & Justice - laws, law enforcement, courts, prisons, investigations",
    "Social Issues - poverty, homelessness, human rights, community service",
    "Technology - computers, engineering, artificial intelligence, innovations",
    "Entertainment - movies, television, games, comedy, performing arts",
]


TOPICS_CODE = [
    "Fundamentals of Programming: Introduction to programming concepts, data types, variables, control structures, and algorithms.",
    "Fundamentals of Programming: Understanding programming paradigms (procedural, object-oriented, functional, and declarative).",
    "Fundamentals of Programming: Exploring different programming languages (e.g., Python, Java, C++, JavaScript, etc.).",
    "Data Structures and Algorithms: Study of fundamental data structures (arrays, linked lists, trees, graphs, etc.).",
    "Data Structures and Algorithms: Analysis of algorithm complexity and performance optimization techniques.",
    "Data Structures and Algorithms: Implementation of common algorithms (sorting, searching, graph traversal, etc.).",
    "Computer Architecture and Operating Systems: Understanding computer organization, memory management, and CPU operation.",
    "Computer Architecture and Operating Systems: Exploring operating system concepts, process management, and file systems.",
    "Computer Architecture and Operating Systems: Parallel and distributed computing architectures.",
    "Software Engineering Principles: Software development life cycle (SDLC) and software design methodologies.",
    "Software Engineering Principles: Version control systems and collaborative development practices.",
    "Software Engineering Principles: Software testing, debugging, and quality assurance techniques.",
    "Object-Oriented Programming (OOP): In-depth study of OOP concepts (classes, objects, inheritance, polymorphism, etc.).",
    "Object-Oriented Programming (OOP): Design patterns and best practices for object-oriented design.",
    "Object-Oriented Programming (OOP): Advanced topics like metaprogramming and reflection.",
    "Functional Programming: Functional programming paradigm and its core concepts (pure functions, immutability, etc.).",
    "Functional Programming: Higher-order functions, closures, and lambda expressions.",
    "Functional Programming: Exploration of functional programming languages (Haskell, Erlang, Clojure, etc.).",
    "Databases and Data Management: Relational database management systems (RDBMS) and SQL.",
    "Databases and Data Management: NoSQL databases (key-value, document, columnar, and graph databases).",
    "Databases and Data Management: Data modeling, normalization, and query optimization techniques.",
    "Web Development: Front-end technologies (HTML, CSS, JavaScript, frameworks like React, Angular, Vue.js).",
    "Web Development: Back-end technologies (Node.js, Django, Ruby on Rails, ASP.NET, etc.).",
    "Web Development: Web services, RESTful APIs, and server-side scripting.",
    "Mobile App Development: Native mobile app development (iOS with Swift, Android with Kotlin/Java).",
    "Mobile App Development: Cross-platform mobile frameworks (React Native, Flutter, Xamarin).",
    "Mobile App Development: Mobile app architecture, performance optimization, and testing.",
    "Computer Networks and Cybersecurity: Network protocols, models (OSI and TCP/IP), and communication principles.",
    "Computer Networks and Cybersecurity: Cybersecurity concepts (encryption, authentication, access control, etc.).",
    "Computer Networks and Cybersecurity: Network security techniques (firewalls, VPNs, intrusion detection/prevention).",
    "Parallel and Distributed Computing: Parallel programming models and techniques (threads, processes, message passing).",
    "Parallel and Distributed Computing: Distributed systems concepts (synchronization, consistency, fault tolerance).",
    "Parallel and Distributed Computing: Cloud computing architectures and technologies (serverless, containers, microservices).",
    "Machine Learning and Artificial Intelligence: Introduction to machine learning algorithms (supervised, unsupervised, and reinforcement learning).",
    "Machine Learning and Artificial Intelligence: Neural networks, deep learning, and natural language processing.",
    "Machine Learning and Artificial Intelligence: Integration of AI models into applications and ethical considerations.",
    "Computer Graphics and Multimedia: 2D and 3D graphics rendering techniques and APIs (OpenGL, DirectX, WebGL).",
    "Computer Graphics and Multimedia: Image and video processing algorithms and multimedia formats.",
    "Computer Graphics and Multimedia: Virtual and augmented reality technologies and applications.",
    "Game Development: Game engines and frameworks (Unity, Unreal Engine, Godot, etc.).",
    "Game Development: Game design principles, game mechanics, and level design.",
    "Game Development: Multiplayer game development and networking considerations.",
    "Embedded Systems and Internet of Things (IoT): Embedded system architectures and programming languages (C, C++, Rust).",
    "Embedded Systems and Internet of Things (IoT): IoT protocols, communication standards, and device management.",
    "Embedded Systems and Internet of Things (IoT): Sensor data processing and real-time system design.",
    "Compilers and Interpreters: Lexical analysis, syntax analysis, and semantic analysis.",
    "Compilers and Interpreters: Code generation, optimization techniques, and virtual machines.",
    "Compilers and Interpreters: Design and implementation of programming languages.",
    "Software Testing and Quality Assurance: Testing methodologies (unit testing, integration testing, system testing, etc.).",
    "Software Testing and Quality Assurance: Test-driven development (TDD) and behavior-driven development (BDD).",
    "Software Testing and Quality Assurance: Automated testing frameworks and continuous integration/delivery (CI/CD) pipelines.",
    "DevOps and Site Reliability Engineering: Infrastructure as Code (IaC) and configuration management tools (Terraform, Ansible, Puppet).",
    "DevOps and Site Reliability Engineering: Containerization technologies (Docker, Kubernetes) and container orchestration.",
    "DevOps and Site Reliability Engineering: Monitoring, logging, and performance optimization techniques.",
    "Open Source Development and Collaboration: Understanding open-source software licenses and communities.",
    "Open Source Development and Collaboration: Contribution to open-source projects and best practices.",
    "Open Source Development and Collaboration: Collaborative coding platforms and tools (GitHub, GitLab, etc.).",
    "Emerging Technologies and Future Trends: Blockchain and distributed ledger technologies.",
    "Emerging Technologies and Future Trends: Quantum computing and its potential impact on cryptography and algorithms.",
    "Emerging Technologies and Future Trends: Ethical considerations and responsible development of AI systems.",
    "Low-Level Programming and Systems Programming: Assembly language programming and reverse engineering.",
    "Low-Level Programming and Systems Programming: Memory management techniques (manual memory allocation, garbage collection).",
    "Low-Level Programming and Systems Programming: Kernel-level programming and operating system internals.",
    "Scripting Languages and Automation: Scripting languages like Bash, Python, PowerShell, and their applications.",
    "Scripting Languages and Automation: Task automation, system administration, and DevOps scripting.",
    "Scripting Languages and Automation: Text processing and regular expressions.",
    "Domain-Specific Languages (DSLs): Design and implementation of domain-specific languages.",
    "Domain-Specific Languages (DSLs): Language workbenches and language-oriented programming.",
    "Domain-Specific Languages (DSLs): Applications of DSLs in various domains (finance, healthcare, manufacturing, etc.).",
    "Formal Methods and Program Verification: Mathematical foundations of software development (logic, set theory, etc.).",
    "Formal Methods and Program Verification: Model checking, theorem proving, and static program analysis.",
    "Formal Methods and Program Verification: Formal specification languages and tools (TLA+, Alloy, etc.).",
    "High-Performance Computing (HPC): Parallel programming models and libraries (OpenMP, MPI, CUDA, etc.).",
    "High-Performance Computing (HPC): Performance optimization techniques (vectorization, cache optimization, etc.).",
    "High-Performance Computing (HPC): HPC architectures and applications (supercomputers, clusters, grids).",
    "Computational Science and Scientific Computing: Numerical methods and scientific computing libraries (NumPy, SciPy, etc.).",
    "Computational Science and Scientific Computing: Simulations and modeling in various scientific domains.",
    "Computational Science and Scientific Computing: Visualization and data analysis tools for scientific data.",
    "Mixed Reality (XR) Development: Virtual Reality (VR), Augmented Reality (AR), and Mixed Reality (MR) technologies.",
    "Mixed Reality (XR) Development: XR development frameworks and tools (Unity, Unreal Engine, ARCore, ARKit).",
    "Mixed Reality (XR) Development: XR user experience design and interaction techniques.",
    "Computer Vision and Image Processing: Image acquisition, representation, and preprocessing techniques.",
    "Computer Vision and Image Processing: Object detection, recognition, and tracking algorithms.",
    "Computer Vision and Image Processing: Applications of computer vision in various domains (robotics, surveillance, medical imaging, etc.).",
    "Natural Language Processing (NLP): Text preprocessing, tokenization, and stemming/lemmatization.",
    "Natural Language Processing (NLP): Language models, sentiment analysis, and text classification.",
    "Natural Language Processing (NLP): Dialogue systems, question answering, and language generation.",
    "Blockchain and Decentralized Applications: Blockchain architectures and consensus mechanisms (Proof-of-Work, Proof-of-Stake).",
    "Blockchain and Decentralized Applications: Smart contract development and decentralized application (DApp) design.",
    "Blockchain and Decentralized Applications: Cryptographic principles and techniques used in blockchain systems.",
]
